update deploy.sh default script

diff --git a/besync b/besync
--- a/besync
+++ b/besync
@@ -66,7 +66,7 @@ SCRIPT_NAME="$(basename "$0")"
 SCRIPT_PATH="$(realpath "$0")"
 
 FILE="besync"
-VERSION="1.2.14"
+VERSION="1.2.15"
 DESCRIPTION="Script for synchronizing files between a local directory and a remote server using rsync and SSH. It includes features like backup, deploy, rotate."
 
 UPDATE_URL="https://sh.stack.pl/besync"
@@ -387,25 +387,37 @@ save_external_deploy_script() {
             echo
             echo "# The following is an example of how this file can look with custom commands:"
             echo
-            echo "#   echo ====== Step 1/4: Build the project ...  ======"   
-            echo "#   cd $HOME/project/"
-            echo "#   npm run build"
-            echo "#   if [[ \$? -ne 0 ]]; then"
-            echo "#       echo \"Build failed. Aborting deployment.\""
-            echo "#       exit 1"
-            echo "#   fi"
+            echo "# echo ====== Step 1/4: Build the project ...  ======"   
+            echo "# cd $HOME/project/"
+            echo "# npm run build"
+            echo "# if [[ \$? -ne 0 ]]; then"
+            echo "#     echo \"Build failed. Aborting deployment.\""
+            echo "#     exit 1"
+            echo "# fi"
             echo ""
-            echo "#   echo ====== Step 2/4: Start SSH agent to add your SSH key to the agent ...  ======"
-            echo "#   eval \$(ssh-agent)"
-            echo "#   ssh-add ~/.ssh/id_ed25519"
+            echo "# echo ====== Step 2/4: Start SSH agent and add your SSH deploy key to the agent ...  ======"
+            echo "# eval \$(ssh-agent)"
+            echo "# ssh-add ~/.ssh/id_ed25519"
             echo ""
-            echo "#   echo ====== Step 3/4: Deploy the result of build to the server ...  ======"
-            echo "#   rsync -avz -e ssh --partial $HOME/project/dist/ $remote_ssh_user@$remote_ssh_host:$remote_dir/assets/"
+            echo "# echo ====== Step 3/4: Deploy the result of build to the server (rsync local -> server) ...  ======"
+            echo "# rsync -avz -e ssh --partial $HOME/project/dist/ $remote_ssh_user@$remote_ssh_host:$remote_dir/assets/"
             echo ""
-            echo "#   echo ====== Step 4/4: Deploy other static files like index.html and images ...  ======"
-            echo "#   rsync -avz -e ssh --partial --include=\"*/\" --include=\"images/\" --exclude=\"*\" $HOME/project/ $remote_ssh_user@$remote_ssh_host:$remote_dir/"
+            echo "# if [[ \$? -ne 0 ]]; then"
+            echo "#     echo \"Deployment failed.\""
+            echo "#     exit 1"
+            echo "# fi"
             echo ""
-            echo "#   echo Deployment completed successfully."
+            echo "# echo ====== Step 4/4: Deploy other files like images (rsync local -> server) ...  ======"
+            echo "# rsync -avz -e ssh --partial --include=\"*/\" --include=\"images/\" --exclude=\"*\" $HOME/project/ $remote_ssh_user@$remote_ssh_host:$remote_dir/"
+            echo ""
+            echo "# if [[ \$? -ne 0 ]]; then"
+            echo "#     echo \"Deployment failed.\""
+            echo "#     exit 1"
+            echo "# else"
+            echo "#     echo =================================="
+            echo "#     echo Deployment completed successfully."
+            echo "#     echo =================================="
+            echo "# fi"
         } > $external_script_file
         chmod +x $external_script_file
         echo
